//var shuffleSequence = seq("intro", sepWith("sep", seq("practice", rshuffle("s1", "s2"))), sepWith("sep", rshuffle("q1", "q2")));
var shuffleSequence = sepWith("sep", seq(anyType));
//var shuffleSequence = seq("intro", sepWith("sep", seq("practice", shuffle("s1", shuffle("l1","l2","l3"))))
var practiceItemTypes = ["practice"];

var defaults = [
    "Separator", {
        transfer: 300,
        normalMessage: "Ожидание",
        errorMessage: "Неверно"
    },
    "DashedSentence", {
        mode: "self-paced reading"
    },
    "AcceptabilityJudgment", {
        as: ["1", "9"],
        hasCorrect: 1,
        presentAsScale: true,
        instructions: "Используйте клавиатуру или нажмите на ответ",
        leftComment: "(Бессмысленное)", rightComment: "(Осмысленное)"
    },
    "Question", {
        hasCorrect: true,
        randomOrder: false
    },
    "Message", {
        hideProgressBar: true
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: true
    }
];

var items = [

    // New in Ibex 0.3-beta-9. You can now add a '__SendResults__' controller in your shuffle
    // sequence to send results before the experiment has finished. This is NOT intended to allow
    // for incremental sending of results -- you should send results exactly once per experiment.
    // However, it does permit additional messages to be displayed to participants once the
    // experiment itself is over. If you are manually inserting a '__SendResults__' controller into
    // the shuffle sequence, you must set the 'manualSendResults' configuration variable to 'true', since
    // otherwise, results are automatically sent at the end of the experiment.
    //
    //["sr", "__SendResults__", { }],

    ["sep", "Separator", { }],

    // New in Ibex 0.3-beta19. You can now determine the point in the experiment at which the counter
    // for latin square designs will be updated. (Previously, this was always updated upon completion
    // of the experiment.) To do this, insert the special '__SetCounter__' controller at the desired
    // point in your running order. If given no options, the counter is incremented by one. If given
    // an 'inc' option, the counter is incremented by the specified amount. If given a 'set' option,
    // the counter is set to the given number. (E.g., { set: 100 }, { inc: -1 })
    //
    //["setcounter", "__SetCounter__", { }],

    // NOTE: You could also use the 'Message' controller for the experiment intro (this provides a simple
    // consent checkbox).

    ["intro", "Form", {
        html: { include: "example_intro.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Bad value for \u2018age\u2019"; }
        }
    } ],

    //
    // Three practice items for self-paced reading (one with a comprehension question).
    //
//     ["practice", "DashedSentence", {s: "This is a practice sentence to get you used to reading sentences like this."}],
//     ["practice", "DashedSentence", {s: "This is another practice sentence with a practice question following it."},
//                  "Question", {hasCorrect: false, randomOrder: false,
//                               q: "How would you like to answer this question?",
//                               as: ["Press 1 or click here for this answer.",
//                                    "Press 2 or click here for this answer.",
//                                    "Press 3 or click here for this answer."]}],
    ["practice", "AcceptabilityJudgment", {s: "Это тренировочные словосочетания. Начинайте оценивать осмысленность."}],
    ["practice", "AcceptabilityJudgment", {s: "тренировочное словосочетание"}],
    ["practice", "AcceptabilityJudgment", {s: "глупый кролик"}],
    ["practice", "AcceptabilityJudgment", {s: "глупый мальчик"}],
    ["practice", "AcceptabilityJudgment", {hasCorrect: 0, s: "вяленый музей"}],
    ["practice", "AcceptabilityJudgment", {s: "вяленый окунь"}],
    ["practice", "AcceptabilityJudgment", {s: "Это последнее тренировочное предложение"}],
    
//     ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"несметное ведро"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"несметное дерево"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"лохматый пес"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лохматый слепок"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"острая пила"}],	["с(1-м)", "AcceptabilityJudgment", { s:"острая вражда"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нещадное яблоко"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нещадное желе"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"крупное животное"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"крупное время"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"тупая бритва"}],	["с (1-1)", "AcceptabilityJudgment", { s:"тупая сабля"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукротимый лапоть"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукротимый пенал"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"старшее поколение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старшее манго"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"жесткая шина"}],	["с(1-2)", "AcceptabilityJudgment", { s:"жесткая губка"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"небесное колено"}],	["ф(бо)", "AcceptabilityJudgment", { s:"небесное светило"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"бездонное дупло"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бездонное крыло"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"мягкая глина"}],	["с(1-м)", "AcceptabilityJudgment", { s:"мягкая мера"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"обильный велосипед"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"обильный канцлер"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"территориальное разногласие"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"территориальное плие"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"нежная щека"}],	["с(1-1)", "AcceptabilityJudgment", { s:"нежная шея"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"комплексное филе"}],	["ф(бо)", "AcceptabilityJudgment", { s:"комплексное оздоровление"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"галопирующий нос"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"галопирующий пароль"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"толстая нога"}],	["с(1-2)", "AcceptabilityJudgment", { s:"толстая стена"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нерасторжимое пиво"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нерасторжимое топливо"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"дежурное отделение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"дежурное солнце"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"тонкая пластинка"}],	["с (1-м)", "AcceptabilityJudgment", { s:"тонкая натура"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"ночное масло"}],	["ф(бо)", "AcceptabilityJudgment", { s:"ночное ограбление"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"голодное мясо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"голодное словоблудие"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"узкая кровать"}],	["с(1-1)", "AcceptabilityJudgment", { s:"узкая доска"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"трехколесный свитер"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"трехколесный кефир"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"сильное прощение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"сильное чувство"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"широкий экран"}],	["с(1-2)", "AcceptabilityJudgment", { s:"широкий проход"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"всепоглощающий карандаш"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"всепоглощающий венчик"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"шерстяной плед"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шерстяной магнит"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"мелкая река"}],	["с (1-м)", "AcceptabilityJudgment", { s:"мелкая ссора"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старательный веер"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старательный зонтик"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бурное плечо"}],	["ф(бо)", "AcceptabilityJudgment", { s:"бурное течение"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"скользкая палуба"}],	["с (1-1)", "AcceptabilityJudgment", { s:"скользкая улица"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"внешний вид"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"внешний раз"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неустанный стул"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неустанный пистолет"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"пустая койка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"пустая рюмка"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"перочинный пандус"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"перочинный климат"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"научный подход"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"научный стручок"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"полная обойма"}],	["с (1-м)", "AcceptabilityJudgment", { s:"полная чепуха"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молодой калибр"}],	["ф(бо)", "AcceptabilityJudgment", { s:"молодой человек"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судный инкубатор"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судный окрас"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"старая барыня"}],	["с (1-1)", "AcceptabilityJudgment", { s:"старая береза"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молниеносное пончо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молниеносное колье"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"глубокий хомяк"}],	["ф(бо)", "AcceptabilityJudgment", { s:"глубокий грот"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"новая схема"}],	["с(1-2)", "AcceptabilityJudgment", { s:"новая жена"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"балетный станок"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"балетный океан"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"далекий рот"}],	["ф(бо)", "AcceptabilityJudgment", { s:"далекий пик"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"свежая зелень"}],	["с (1-м)", "AcceptabilityJudgment", { s:"свежая рана"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шквальный кошелек"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шквальный ящик"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"готовый крем"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"готовый рост"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"сырая картошка"}],	["с (1-1)", "AcceptabilityJudgment", { s:"сырая капуста"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"мировой йогурт"}],	["ф(бо)", "AcceptabilityJudgment", { s:"мировой заговор"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"отдельный номер"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"отдельный сом"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"влажная салфетка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"влажная погода"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"настоятельное полено"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"настоятельное крем-брюле"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"часовой механизм"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"часовой буддизм"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"сухая ладошка"}],	["с (1-м)", "AcceptabilityJudgment", { s:"сухая старушка"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"отпетый самолет"}],	["ф(бо)", "AcceptabilityJudgment", { s:"отпетый преступник"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"азартное возбуждение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"азартное какао"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"легкое судно"}],	["с (1-1)", "AcceptabilityJudgment", { s:"легкое крыло"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"пущее варенье"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"пущее ремесло"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"одноразовый килограмм"}],	["ф(бо)", "AcceptabilityJudgment", { s:"одноразовый стаканчик"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"чистое белье"}],	["с(1-2)", "AcceptabilityJudgment", { s:"чистое поле"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"железный занавес"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"железный переезд"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"раннее сукно"}],	["ф(бо)", "AcceptabilityJudgment", { s:"раннее утро"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"грязная чашка"}],	["с (1-м)", "AcceptabilityJudgment", { s:"грязная ругань"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"босоногий эликсир"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"босоногий костер"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"женское счастье"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женское сено"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"густая сметана"}],	["с (1-1)", "AcceptabilityJudgment", { s:"густая кашица"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заднее радио"}],	["ф(бо)", "AcceptabilityJudgment", { s:"заднее сидение"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"высшее общество"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"высшее купание"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"теплая труба"}],	["с(1-2)", "AcceptabilityJudgment", { s:"теплая нотка"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женатый тротил"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женатый мел"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"разводной лось"}],	["ф(бо)", "AcceptabilityJudgment", { s:"разводной мост"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"холодный чай"}],	["с (1-м)", "AcceptabilityJudgment", { s:"холодный тон"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"массовый бунт"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"массовый ноготь"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"морское лицо"}],	["ф(бо)", "AcceptabilityJudgment", { s:"морское дно"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"сладкая булочка"}],	["с (1-1)", "AcceptabilityJudgment", { s:"сладкая ягода"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лавровый плач"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лавровый вертолет"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"страховое агенство"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"страховое темя"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"тяжелый кирпич"}],	["с(1-2)", "AcceptabilityJudgment", { s:"тяжелый купол"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"жаркое удостоверение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"жаркое лето"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"безапелляционный нос"}],	["ф(бо)", "AcceptabilityJudgment", { s:"безапелляционный ответ"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"горькая редька"}],	["с (1-м)", "AcceptabilityJudgment", { s:"горькая шутка"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шариковое сомнение"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шариковое побережье"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"активный отдых"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"активный штатив"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"гладкая площадка"}],	["с (1-1)", "AcceptabilityJudgment", { s:"гладкая лысина"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"правый день"}],	["ф(бо)", "AcceptabilityJudgment", { s:"правый глаз"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"здоровый сон"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"здоровый бред"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"грубая веревка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"грубая музыка"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукоснительный крем"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукоснительный фен"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"письменное цунами"}],	["ф(бо)", "AcceptabilityJudgment", { s:"письменное задание"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"яркая свеча"}],	["с (1-м)", "AcceptabilityJudgment", { s:"яркая внешность"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"короткий день"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"короткий мозг"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"проливное путешествие"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"проливное печенье"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"резкая вспышка"}],	["с (1-1)", "AcceptabilityJudgment", { s:"резкая краска"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"судебное решение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судебное метро"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"надрывное село"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"надрывное мыло"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"высокий каблук"}],	["с(1-2)", "AcceptabilityJudgment", { s:"высокий голос"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"огромное мнение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"огромное число"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"паническое яйцо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"паническое мясо"}],
// ["с (1-м)", "AcceptabilityJudgment", { s:"низкая трава"}],	["с (1-м)", "AcceptabilityJudgment", { s:"низкая ступень"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"боевой топор"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"боевой карман"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"непробудное меню"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"непробудное соленье"}],
// ["с (1-1)", "AcceptabilityJudgment", { s:"ровное плоскогорье"}],	["с (1-1)", "AcceptabilityJudgment", { s:"ровное покрытие"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"астрономический плов"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"астрономический окурок"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заклятое весло"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заклятое изменение"}],

	
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"несметное ведро"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"несметное дерево"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"лохматый пес"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лохматый слепок"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"острая пила"}],	["с(1-2)", "AcceptabilityJudgment", { s:"острая шпага"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нещадное яблоко"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нещадное желе"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"крупное животное"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"крупное время"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"тупая бритва"}],	["с(1-м)", "AcceptabilityJudgment", { s:"тупая тоска"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукротимый лапоть"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукротимый пенал"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"старшее поколение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старшее манго"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"жесткая шина"}],	["с(1-1)", "AcceptabilityJudgment", { s:"жесткая палка"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"небесное колено"}],	["ф(бо)", "AcceptabilityJudgment", { s:"небесное светило"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"бездонное дупло"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бездонное крыло"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"мягкая глина"}],	["с(1-2)", "AcceptabilityJudgment", { s:"мягкая хвоя"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"обильный велосипед"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"обильный канцлер"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"территориальное разногласие"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"территориальное плие"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"нежная щека"}],	["с(1-м)", "AcceptabilityJudgment", { s:"нежная душа"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"комплексное филе"}],	["ф(бо)", "AcceptabilityJudgment", { s:"комплексное оздоровление"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"галопирующий нос"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"галопирующий пароль"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"толстая нога"}],	["с(1-1)", "AcceptabilityJudgment", { s:"толстая шея"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нерасторжимое пиво"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нерасторжимое топливо"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"дежурное отделение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"дежурное солнце"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"тонкая пластинка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"тонкая цепочка"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"ночное масло"}],	["ф(бо)", "AcceptabilityJudgment", { s:"ночное ограбление"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"голодное мясо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"голодное словоблудие"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"узкая кровать"}],	["с(1-м)", "AcceptabilityJudgment", { s:"узкая сфера"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"трехколесный свитер"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"трехколесный кефир"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"сильное прощение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"сильное чувство"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"широкий экран"}],	["с(1-1)", "AcceptabilityJudgment", { s:"широкий проспект"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"всепоглощающий карандаш"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"всепоглощающий венчик"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"шерстяной плед"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шерстяной магнит"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"мелкая река"}],	["с(1-2)", "AcceptabilityJudgment", { s:"мелкая щепка"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старательный веер"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старательный зонтик"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бурное плечо"}],	["ф(бо)", "AcceptabilityJudgment", { s:"бурное течение"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"скользкая палуба"}],	["с(1-м)", "AcceptabilityJudgment", { s:"скользкая улыбка"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"внешний вид"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"внешний раз"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неустанный стул"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неустанный пистолет"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"пустая койка"}],	["с(1-1)", "AcceptabilityJudgment", { s:"пустая сцена"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"перочинный пандус"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"перочинный климат"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"научный подход"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"научный стручок"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"полная обойма"}],	["с(1-2)", "AcceptabilityJudgment", { s:"полная комната"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молодой калибр"}],	["ф(бо)", "AcceptabilityJudgment", { s:"молодой человек"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судный инкубатор"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судный окрас"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"старая барыня"}],	["с(1-м)", "AcceptabilityJudgment", { s:"старая привычка"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молниеносное пончо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молниеносное колье"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"глубокий хомяк"}],	["ф(бо)", "AcceptabilityJudgment", { s:"глубокий грот"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"новая схема"}],	["с(1-1)", "AcceptabilityJudgment", { s:"новая пьеса"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"балетный станок"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"балетный океан"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"далекий рот"}],	["ф(бо)", "AcceptabilityJudgment", { s:"далекий пик"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"свежая зелень"}],	["с(1-2)", "AcceptabilityJudgment", { s:"свежая вода"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шквальный кошелек"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шквальный ящик"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"готовый крем"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"готовый рост"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"сырая картошка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"сырая идея"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"мировой йогурт"}],	["ф(бо)", "AcceptabilityJudgment", { s:"мировой заговор"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"отдельный номер"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"отдельный сом"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"влажная салфетка"}],	["с(1-1)", "AcceptabilityJudgment", { s:"влажная простыня"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"настоятельное полено"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"настоятельное крем-брюле"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"часовой механизм"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бурный течение"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"сухая ладошка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"сухая долина"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"отпетый самолет"}],	["ф(бо)", "AcceptabilityJudgment", { s:"отпетый преступник"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"азартное возбуждение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"азартное какао"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"легкое судно"}],	["с(1-м)", "AcceptabilityJudgment", { s:"легкое слово"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"пущее варенье"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"пущее ремесло"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"одноразовый килограмм"}],	["ф(бо)", "AcceptabilityJudgment", { s:"одноразовый стаканчик"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"чистое белье"}],	["с(1-1)", "AcceptabilityJudgment", { s:"чистое белье"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"железный занавес"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"железный переезд"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"раннее сукно"}],	["ф(бо)", "AcceptabilityJudgment", { s:"раннее утро"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"грязная чашка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"грязная струя"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"босоногий эликсир"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"босоногий костер"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"женское счастье"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женское сено"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"густая сметана"}],	["с(1-м)", "AcceptabilityJudgment", { s:"густая завеса"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заднее радио"}],	["ф(бо)", "AcceptabilityJudgment", { s:"заднее сидение"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"высшее общество"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"высшее купание"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"теплая труба"}],	["с(1-1)", "AcceptabilityJudgment", { s:"теплая кожа"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женатый тротил"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женатый мел"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"разводной лось"}],	["ф(бо)", "AcceptabilityJudgment", { s:"разводной мост"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"холодный чай"}],	["с(1-2)", "AcceptabilityJudgment", { s:"холодный цвет"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"массовый бунт"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"массовый ноготь"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"морское лицо"}],	["ф(бо)", "AcceptabilityJudgment", { s:"морское дно"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"сладкая булочка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"сладкая дремота"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лавровый плач"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лавровый вертолет"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"страховое агенство"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"страховое темя"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"тяжелый кирпич"}],	["с(1-1)", "AcceptabilityJudgment", { s:"тяжелый камень"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"жаркое удостоверение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"жаркое лето"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"безапелляционный нос"}],	["ф(бо)", "AcceptabilityJudgment", { s:"безапелляционный ответ"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"горькая редька"}],	["с(1-2)", "AcceptabilityJudgment", { s:"горькая трава"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шариковое сомнение"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шариковое побережье"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"активный отдых"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"активный штатив"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"гладкая площадка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"гладкая версия"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"правый день"}],	["ф(бо)", "AcceptabilityJudgment", { s:"правый глаз"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"здоровый сон"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"здоровый бред"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"грубая веревка"}],	["с(1-1)", "AcceptabilityJudgment", { s:"грубая текстура"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукоснительный крем"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукоснительный фен"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"письменное цунами"}],	["ф(бо)", "AcceptabilityJudgment", { s:"письменное задание"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"яркая свеча"}],	["с(1-2)", "AcceptabilityJudgment", { s:"яркая песня"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"короткий день"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"короткий мозг"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"проливное путешествие"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"проливное печенье"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"резкая вспышка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"резкая статья"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"судебное решение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судебное метро"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"надрывное село"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"надрывное мыло"}],
// ["с(1-1)", "AcceptabilityJudgment", { s:"высокий каблук"}],	["с(1-1)", "AcceptabilityJudgment", { s:"высокий берег"}],
// ["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"огромное мнение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"огромное число"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"паническое яйцо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"паническое мясо"}],
// ["с(1-2)", "AcceptabilityJudgment", { s:"низкая трава"}],	["с(1-2)", "AcceptabilityJudgment", { s:"низкая нота"}],
// ["ф(об)", "AcceptabilityJudgment", { s:"боевой топор"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"боевой карман"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"непробудное меню"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"непробудное соленье"}],
// ["с(1-м)", "AcceptabilityJudgment", { s:"ровное плоскогорье"}],	["с(1-м)", "AcceptabilityJudgment", { s:"ровное спокойствие"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"астрономический плов"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"астрономический окурок"}],
// ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заклятое весло"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заклятое изменение"}],
// 	

    ["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"несметное ведро"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"несметное дерево"}],
["ф(об)", "AcceptabilityJudgment", { s:"лохматый пес"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лохматый слепок"}],
["с(1-1)", "AcceptabilityJudgment", { s:"острая пила"}],	["с(1-1)", "AcceptabilityJudgment", { s:"острая коса"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нещадное яблоко"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нещадное желе"}],
["ф(об)", "AcceptabilityJudgment", { s:"крупное животное"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"крупное время"}],
["с(1-2)", "AcceptabilityJudgment", { s:"тупая бритва"}],	["с(1-2)", "AcceptabilityJudgment", { s:"тупая палка"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукротимый лапоть"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукротимый пенал"}],
["ф(об)", "AcceptabilityJudgment", { s:"старшее поколение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старшее манго"}],
["с(1-м)", "AcceptabilityJudgment", { s:"жесткая шина"}],	["с(1-м)", "AcceptabilityJudgment", { s:"жесткая воля"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"небесное колено"}],	["ф(бо)", "AcceptabilityJudgment", { s:"небесное светило"}],
["ф(об)", "AcceptabilityJudgment", { s:"бездонное дупло"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бездонное крыло"}],
["с(1-1)", "AcceptabilityJudgment", { s:"мягкая глина"}],	["с(1-1)", "AcceptabilityJudgment", { s:"мягкая ветка"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"обильный велосипед"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"обильный канцлер"}],
["ф(об)", "AcceptabilityJudgment", { s:"территориальное разногласие"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"территориальное плие"}],
["с(1-2)", "AcceptabilityJudgment", { s:"нежная щека"}],	["с(1-2)", "AcceptabilityJudgment", { s:"нежная мякоть"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"комплексное филе"}],	["ф(бо)", "AcceptabilityJudgment", { s:"комплексное оздоровление"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"галопирующий нос"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"галопирующий пароль"}],
["с(1-м)", "AcceptabilityJudgment", { s:"толстая нога"}],	["с(1-м)", "AcceptabilityJudgment", { s:"толстая шутка"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нерасторжимое пиво"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"нерасторжимое топливо"}],
["ф(об)", "AcceptabilityJudgment", { s:"дежурное отделение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"дежурное солнце"}],
["с(1-1)", "AcceptabilityJudgment", { s:"тонкая пластинка"}],	["с(1-1)", "AcceptabilityJudgment", { s:"тонкая рубашка"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"ночное масло"}],	["ф(бо)", "AcceptabilityJudgment", { s:"ночное ограбление"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"голодное мясо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"голодное словоблудие"}],
["с(1-2)", "AcceptabilityJudgment", { s:"узкая кровать"}],	["с(1-2)", "AcceptabilityJudgment", { s:"узкая прорезь"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"трехколесный свитер"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"трехколесный кефир"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"сильное прощение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"сильное чувство"}],
["с(1-м)", "AcceptabilityJudgment", { s:"широкий экран"}],	["с(1-м)", "AcceptabilityJudgment", { s:"широкий доступ"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"всепоглощающий карандаш"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"всепоглощающий венчик"}],
["ф(об)", "AcceptabilityJudgment", { s:"шерстяной плед"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шерстяной магнит"}],
["с(1-1)", "AcceptabilityJudgment", { s:"мелкая река"}],	["с(1-1)", "AcceptabilityJudgment", { s:"мелкая лужа"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старательный веер"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"старательный зонтик"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"бурное плечо"}],	["ф(бо)", "AcceptabilityJudgment", { s:"бурное течение"}],
["с(1-2)", "AcceptabilityJudgment", { s:"скользкая палуба"}],	["с(1-2)", "AcceptabilityJudgment", { s:"скользкая лягушка"}],
["ф(об)", "AcceptabilityJudgment", { s:"внешний вид"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"внешний раз"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неустанный стул"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неустанный пистолет"}],
["с(1-м)", "AcceptabilityJudgment", { s:"пустая койка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"пустая мечта"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"перочинный пандус"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"перочинный климат"}],
["ф(об)", "AcceptabilityJudgment", { s:"научный подход"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"научный стручок"}],
["с(1-1)", "AcceptabilityJudgment", { s:"полная обойма"}],	["с(1-1)", "AcceptabilityJudgment", { s:"полная корзинка"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молодой калибр"}],	["ф(бо)", "AcceptabilityJudgment", { s:"молодой человек"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судный инкубатор"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судный окрас"}],
["с(1-2)", "AcceptabilityJudgment", { s:"старая барыня"}],	["с(1-2)", "AcceptabilityJudgment", { s:"старая квартира"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молниеносное пончо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"молниеносное колье"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"глубокий хомяк"}],	["ф(бо)", "AcceptabilityJudgment", { s:"глубокий грот"}],
["с(1-м)", "AcceptabilityJudgment", { s:"новая схема"}],	["с(1-м)", "AcceptabilityJudgment", { s:"новая волна"}],
["ф(об)", "AcceptabilityJudgment", { s:"балетный станок"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"балетный океан"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"далекий рот"}],	["ф(бо)", "AcceptabilityJudgment", { s:"далекий пик"}],
["с(1-1)", "AcceptabilityJudgment", { s:"свежая зелень"}],	["с(1-1)", "AcceptabilityJudgment", { s:"свежая рыба"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шквальный кошелек"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шквальный ящик"}],
["ф(об)", "AcceptabilityJudgment", { s:"готовый крем"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"готовый рост"}],
["с(1-2)", "AcceptabilityJudgment", { s:"сырая картошка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"сырая прохлада"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"мировой йогурт"}],	["ф(бо)", "AcceptabilityJudgment", { s:"мировой заговор"}],
["ф(об)", "AcceptabilityJudgment", { s:"отдельный номер"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"отдельный сом"}],
["с(1-м)", "AcceptabilityJudgment", { s:"влажная салфетка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"влажная улыбка"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"настоятельное полено"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"настоятельное крем-брюле"}],
["ф(об)", "AcceptabilityJudgment", { s:"часовой механизм"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"часовой буддизм"}],
["с(1-1)", "AcceptabilityJudgment", { s:"сухая ладошка"}],	["с(1-1)", "AcceptabilityJudgment", { s:"сухая тропинка"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"отпетый самолет"}],	["ф(бо)", "AcceptabilityJudgment", { s:"отпетый преступник"}],
["ф(об)", "AcceptabilityJudgment", { s:"азартное возбуждение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"азартное какао"}],
["с(1-2)", "AcceptabilityJudgment", { s:"легкое судно"}],	["с(1-2)", "AcceptabilityJudgment", { s:"легкое одеяло"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"пущее варенье"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"пущее ремесло"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"одноразовый килограмм"}],	["ф(бо)", "AcceptabilityJudgment", { s:"одноразовый стаканчик"}],
["с(1-м)", "AcceptabilityJudgment", { s:"чистое белье"}],	["с(1-м)", "AcceptabilityJudgment", { s:"чистое дело"}],
["ф(об)", "AcceptabilityJudgment", { s:"железный занавес"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"железный переезд"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"раннее сукно"}],	["ф(бо)", "AcceptabilityJudgment", { s:"раннее утро"}],
["с(1-1)", "AcceptabilityJudgment", { s:"грязная чашка"}],	["с(1-1)", "AcceptabilityJudgment", { s:"грязная шея"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"босоногий эликсир"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"босоногий костер"}],
["ф(об)", "AcceptabilityJudgment", { s:"женское счастье"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женское сено"}],
["с(1-2)", "AcceptabilityJudgment", { s:"густая сметана"}],	["с(1-2)", "AcceptabilityJudgment", { s:"густая седина"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заднее радио"}],	["ф(бо)", "AcceptabilityJudgment", { s:"заднее сидение"}],
["ф(об)", "AcceptabilityJudgment", { s:"высшее общество"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"высшее купание"}],
["с(1-м)", "AcceptabilityJudgment", { s:"теплая труба"}],	["с(1-м)", "AcceptabilityJudgment", { s:"теплая дружба"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женатый тротил"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"женатый мел"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"разводной лось"}],	["ф(бо)", "AcceptabilityJudgment", { s:"разводной мост"}],
["с(1-1)", "AcceptabilityJudgment", { s:"холодный чай"}],	["с(1-1)", "AcceptabilityJudgment", { s:"холодный лоб"}],
["ф(об)", "AcceptabilityJudgment", { s:"массовый бунт"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"массовый ноготь"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"морское лицо"}],	["ф(бо)", "AcceptabilityJudgment", { s:"морское дно"}],
["с(1-2)", "AcceptabilityJudgment", { s:"сладкая булочка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"сладкая музыка"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лавровый плач"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"лавровый вертолет"}],
["ф(об)", "AcceptabilityJudgment", { s:"страховое агенство"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"страховое темя"}],
["с(1-м)", "AcceptabilityJudgment", { s:"тяжелый кирпич"}],	["с(1-м)", "AcceptabilityJudgment", { s:"тяжелый бой"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"жаркое удостоверение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"жаркое лето"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"безапелляционный нос"}],	["ф(бо)", "AcceptabilityJudgment", { s:"безапелляционный ответ"}],
["с(1-1)", "AcceptabilityJudgment", { s:"горькая редька"}],	["с(1-1)", "AcceptabilityJudgment", { s:"горькая полынь"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шариковое сомнение"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"шариковое побережье"}],
["ф(об)", "AcceptabilityJudgment", { s:"активный отдых"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"активный штатив"}],
["с(1-2)", "AcceptabilityJudgment", { s:"гладкая площадка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"гладкая линия"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"правый день"}],	["ф(бо)", "AcceptabilityJudgment", { s:"правый глаз"}],
["ф(об)", "AcceptabilityJudgment", { s:"здоровый сон"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"здоровый бред"}],
["с(1-м)", "AcceptabilityJudgment", { s:"грубая веревка"}],	["с(1-м)", "AcceptabilityJudgment", { s:"грубая манера"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукоснительный крем"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"неукоснительный фен"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"письменное цунами"}],	["ф(бо)", "AcceptabilityJudgment", { s:"письменное задание"}],
["с(1-1)", "AcceptabilityJudgment", { s:"яркая свеча"}],	["с(1-1)", "AcceptabilityJudgment", { s:"яркая лампа"}],
["ф(об)", "AcceptabilityJudgment", { s:"короткий день"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"короткий мозг"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"проливное путешествие"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"проливное печенье"}],
["с(1-2)", "AcceptabilityJudgment", { s:"резкая вспышка"}],	["с(1-2)", "AcceptabilityJudgment", { s:"резкая нота"}],
["ф(об)", "AcceptabilityJudgment", { s:"судебное решение"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"судебное метро"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"надрывное село"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"надрывное мыло"}],
["с(1-м)", "AcceptabilityJudgment", { s:"высокий каблук"}],	["с(1-м)", "AcceptabilityJudgment", { s:"высокий процент"}],
["ф(бо)", "AcceptabilityJudgment", {hasCorrect: 0, s:"огромное мнение"}],	["ф(бо)", "AcceptabilityJudgment", { s:"огромное число"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"паническое яйцо"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"паническое мясо"}],
["с(1-1)", "AcceptabilityJudgment", { s:"низкая трава"}],	["с(1-1)", "AcceptabilityJudgment", { s:"низкая крыша"}],
["ф(об)", "AcceptabilityJudgment", { s:"боевой топор"}],	["ф(об)", "AcceptabilityJudgment", {hasCorrect: 0, s:"боевой карман"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"непробудное меню"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"непробудное соленье"}],
["с(1-2)", "AcceptabilityJudgment", { s:"ровное плоскогорье"}],	["с(1-2)", "AcceptabilityJudgment", { s:"ровное гудение"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"астрономический плов"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"астрономический окурок"}],
["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заклятое весло"}],	["ф(бб)", "AcceptabilityJudgment", {hasCorrect: 0, s:"заклятое изменение"}],
 	
    //
    // Two "real" (i.e. non-filler) self-paced reading items with corresponding acceptability judgment items.
    // There are two conditions.
    //

//     [["s1",1], "DashedSentence", {s: "The journalist interviewed an actress who he knew to be shy of publicity after meeting on a previous occasion."},
//                "Question",       {q: "The actress was:", as: ["shy", "publicity-seeking", "impatient"]}],
//     [["s2",1], "DashedSentence", {s: "The journalist interviewed an actress who after meeting on a previous occasion he knew to be shy of publicity."},
//                "Question",       {q: "The actress was:", as: ["shy", "publicity-seeking", "impatient"]}],

    // The first question will be chosen if the first sentence from the previous two items is chosen;
    // the second question will be chosen if the second sentence from the previous pair of items is chosen.
//     [["q1",[100,1]], "AcceptabilityJudgment", {s: "Which actress did the journalist interview after meeting her PA on a previous occasion?"}],
//     [["q2",[100,1]], "AcceptabilityJudgment", {s: "Which actress did the journalist interview her husband after meeting on a previous occasion?"}],
// 
//     [["s1",2], "DashedSentence", {s: "The teacher helped struggling students who he encouraged to succeed without treating like idiots."},
//                "Question",       {q: "What did the teacher do?",
//                                   as: ["Encourage struggling students to succeed",
//                                        "Encourage his best students to succeed",
//                                        "Treat struffling students like idiots"]}],
//     [["s2",2], "DashedSentence", {s: "The teacher helped struggling students who without treating like idiots he encouraged to succeed."},
//                "Question",       {q: "What did the teacher do?", as: ["Encourage struggling students to succeed",
//                                                                       "Encourage his best students to succeed",
//                                                                       "Treat struggling students like idiots"]}],
// 
//     [["q1",[200,2]], "AcceptabilityJudgment", {s: {html: "<b>Which struggling students</b> did the teacher encourage to succeed without treating their friends like idiots?"}}],
//     [["q2",[200,2]], "AcceptabilityJudgment", {s: {html: "<b>Which struggling students</b> did the teacher encourage their friends to succeed without treating like idiots?"}}],

    //
    // 10 self-paced-reading filler sentences.
    //

//     ["f", "DashedSentence", {s: "The foreign spy that encoded the top-secret messages was given a new mission that required going to Japan."},
//           "Question",       {q: "The spy's mission required him to:", as: ["Go to Japan", "Destroy top-secret messages", "Bug a hotel room"]}],
// 

];